Add flake8 running to pre-commit hook.
Couple of fixes thereby.

diff --git a/conf/hook-pre-commit b/conf/hook-pre-commit
--- a/conf/hook-pre-commit
+++ b/conf/hook-pre-commit
@@ -32,3 +32,10 @@ if [ -n "$dir_sass" ]; then
     fi
     git add $out
 fi
+
+command -v flake8 >/dev/null 2>&1 || {
+  echo >&2 "flake8 does not appear to be available. Unable to lint code."
+  exit 1
+}
+
+flake8
